### ISSUE TITLE
`test` methods should respect constraints

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary-type-classes#144]
For example, `Array a` satisfies the requirements of [Setoid][1] if and only if `a` satisfies the requirements of Setoid. `Z.Setoid.test` currently ignores this constraint:

```javascript
> var Z = require ('sanctuary-type-classes')

> var Useless = require ('sanctuary-useless')

> Z.Setoid.test (Useless)
false

> Z.Setoid.test ([Useless])
true
```

`Z.Setoid.test ([])` and `Z.Setoid.test ([1, 2, 3])` should evaluate `true` but `Z.Setoid.test ([Useless])` should evaluate `false`. The behaviour of other `test` methods should also change.

[1]: https://github.com/fantasyland/fantasy-land/#setoid

**Comment by Avaq** [comment]
Yeah. The current implementation relies on a method being "available":

https://github.com/sanctuary-js/sanctuary-type-classes/blob/15a15fcda963a9200f2bf93296a8a267304c5945/index.js#L285
https://github.com/sanctuary-js/sanctuary-type-classes/blob/15a15fcda963a9200f2bf93296a8a267304c5945/index.js#L268
https://github.com/sanctuary-js/sanctuary-type-classes/blob/15a15fcda963a9200f2bf93296a8a267304c5945/index.js#L241

For custom types, this works, because they can hide their method to signal that it does not support the typeclass. Or in other words: `x` is allowed to carry information that determines the end result.

For Z-provided type classes, we default to a lookup in a statically defined list of methods:

https://github.com/sanctuary-js/sanctuary-type-classes/blob/15a15fcda963a9200f2bf93296a8a267304c5945/index.js#L269

Because the list is statically defined, the actual value (`x`) has no influence over the outcome.

The simplest solution would have us compute the class implementations given the value:

```diff
-  (funcPath ([type (x), 'prototype', name], implementations));
+  (funcPath ([type (x), 'prototype', name], implementations (x)));
```

**Comment by Avaq** [comment]
Once `implementations` itself becomes a function over the value, the structure of the lib could be reevaluated though. For example, why would `implementations (x)` return a structure that we use purely to lookup the class we're interested in. We could consider the following instead:

```diff
-  (funcPath ([type (x), 'prototype', name], implementations (x)));
+  (implementation (x, name));
```
